// Mock data for demo purposes

export const INCIDENT_TYPES = [
  'Road Accident',
  'Fire',
  'Flood',
  'Medical Emergency',
  'Earthquake',
  'Building Collapse',
  'Gas Leak',
  'Chemical Spill',
];

export const SEVERITY_LEVELS = ['Critical', 'High', 'Medium', 'Low'];

export const STATUS_OPTIONS = ['Pending', 'Assigned', 'In Progress', 'Resolved', 'Closed'];

export const MOCK_INCIDENTS = [
  {
    id: 'INC-001',
    title: 'Major Highway Pile-up on NH48',
    type: 'Road Accident',
    description: 'A multi-vehicle collision involving 5 cars and a truck near Toll Plaza. Multiple people injured, heavy bleeding reported. Traffic completely blocked. At least 3 people are trapped inside vehicles.',
    severity: 'Critical',
    status: 'In Progress',
    location: 'NH48, Near Huda City Centre, Gurugram',
    contactNumber: '+91 9876543210',
    reportedBy: 'citizen-001',
    reporterName: 'Rahul Sharma',
    confidence: 0.94,
    priorityScore: 1,
    imageUrl: null,
    createdAt: '2026-07-21T05:30:00Z',
    updatedAt: '2026-07-21T06:15:00Z',
    analysis: {
      incidentType: 'Road Accident',
      severity: 'Critical',
      confidence: 0.94,
      confidencePercent: 94,
      firstAid: [
        'Ensure the scene is safe before approaching.',
        'Call emergency services immediately (112/108).',
        'Do NOT move the injured unless there is immediate danger.',
        'If bleeding, apply firm pressure with a clean cloth.',
      ],
      emergencyServices: ['Ambulance (108)', 'Police (100)', 'Traffic Control', 'Trauma Center'],
      recommendations: [
        'Incident classified as Road Accident with Critical severity.',
        'Immediate dispatch of emergency services recommended.',
        'Alert nearby hospitals for potential incoming casualties.',
      ],
    },
  },
  {
    id: 'INC-002',
    title: 'Warehouse Fire in Industrial Area',
    type: 'Fire',
    description: 'Large fire engulfing a chemical storage warehouse in MIDC industrial area. Heavy smoke visible from 2km. Workers have been evacuated but two are reported missing.',
    severity: 'Critical',
    status: 'Assigned',
    location: 'MIDC Industrial Area, Phase 2, Pune',
    contactNumber: '+91 9876543211',
    reportedBy: 'citizen-002',
    reporterName: 'Priya Patel',
    confidence: 0.91,
    priorityScore: 1,
    imageUrl: null,
    createdAt: '2026-07-21T04:45:00Z',
    updatedAt: '2026-07-21T05:00:00Z',
    analysis: {
      incidentType: 'Fire',
      severity: 'Critical',
      confidence: 0.91,
      confidencePercent: 91,
      firstAid: [
        'Evacuate the area immediately.',
        'Call the fire department (101).',
        'If clothing is on fire: STOP, DROP, and ROLL.',
      ],
      emergencyServices: ['Fire Department (101)', 'Ambulance (108)', 'Police (100)'],
      recommendations: [
        'Incident classified as Fire with Critical severity.',
        'Immediate dispatch of fire services recommended.',
      ],
    },
  },
  {
    id: 'INC-003',
    title: 'Elderly Person Collapsed at Market',
    type: 'Medical Emergency',
    description: 'An elderly man approximately 65 years old collapsed at the vegetable market. He appears unconscious and is not responding. Bystanders say he was clutching his chest before falling.',
    severity: 'High',
    status: 'Resolved',
    location: 'Crawford Market, Mumbai',
    contactNumber: '+91 9876543212',
    reportedBy: 'citizen-003',
    reporterName: 'Amit Kumar',
    confidence: 0.87,
    priorityScore: 2,
    imageUrl: null,
    createdAt: '2026-07-20T09:30:00Z',
    updatedAt: '2026-07-20T10:45:00Z',
    analysis: {
      incidentType: 'Medical Emergency',
      severity: 'High',
      confidence: 0.87,
      confidencePercent: 87,
      firstAid: [
        'Call emergency services immediately (112/108).',
        'Check responsiveness — gently shake and shout.',
        'If not breathing, begin CPR.',
      ],
      emergencyServices: ['Ambulance (108)', 'Nearest Hospital'],
      recommendations: [
        'Incident classified as Medical Emergency with High severity.',
        'Dispatch ambulance immediately.',
      ],
    },
  },
  {
    id: 'INC-004',
    title: 'Flash Flooding in Residential Colony',
    type: 'Flood',
    description: 'Heavy rainfall has caused waterlogging in Sector 15 residential colony. Water level is rising to 3 feet in low-lying areas. Several families are stranded on upper floors.',
    severity: 'High',
    status: 'In Progress',
    location: 'Sector 15, Noida',
    contactNumber: '+91 9876543213',
    reportedBy: 'citizen-004',
    reporterName: 'Sneha Reddy',
    confidence: 0.89,
    priorityScore: 2,
    imageUrl: null,
    createdAt: '2026-07-21T02:00:00Z',
    updatedAt: '2026-07-21T03:30:00Z',
    analysis: {
      incidentType: 'Flood',
      severity: 'High',
      confidence: 0.89,
      confidencePercent: 89,
      firstAid: [
        'Move to higher ground immediately.',
        'Do NOT walk or drive through flood waters.',
        'Stay away from power lines.',
      ],
      emergencyServices: ['NDRF', 'Municipal Emergency', 'Ambulance (108)'],
      recommendations: [
        'Incident classified as Flood with High severity.',
        'Dispatch rescue boats and NDRF team.',
      ],
    },
  },
  {
    id: 'INC-005',
    title: 'Minor Gas Smell in Apartment',
    type: 'Gas Leak',
    description: 'Residents on 3rd floor of Sunshine Apartments report a faint gas smell coming from the kitchen area. No visible damage or fire. Area has been ventilated.',
    severity: 'Medium',
    status: 'Pending',
    location: 'Sunshine Apartments, Andheri West, Mumbai',
    contactNumber: '+91 9876543214',
    reportedBy: 'citizen-005',
    reporterName: 'Vikram Singh',
    confidence: 0.78,
    priorityScore: 3,
    imageUrl: null,
    createdAt: '2026-07-21T07:00:00Z',
    updatedAt: '2026-07-21T07:00:00Z',
    analysis: {
      incidentType: 'Gas Leak',
      severity: 'Medium',
      confidence: 0.78,
      confidencePercent: 78,
      firstAid: [
        'Evacuate the area — do NOT use light switches or phones inside.',
        'Open windows and doors while evacuating.',
        'Call gas emergency from outside.',
      ],
      emergencyServices: ['Gas Emergency Service', 'Fire Department (101)'],
      recommendations: [
        'Incident classified as Gas Leak with Medium severity.',
        'Dispatch standard response team.',
      ],
    },
  },
  {
    id: 'INC-006',
    title: 'Two-Wheeler Skid on Wet Road',
    type: 'Road Accident',
    description: 'A motorcycle skidded on the wet road near the bus stop. Rider has minor bruises on arms and legs. Motorcycle has some scratches. No other vehicles involved.',
    severity: 'Low',
    status: 'Closed',
    location: 'MG Road Bus Stop, Bangalore',
    contactNumber: '+91 9876543215',
    reportedBy: 'citizen-001',
    reporterName: 'Rahul Sharma',
    confidence: 0.82,
    priorityScore: 4,
    imageUrl: null,
    createdAt: '2026-07-19T14:20:00Z',
    updatedAt: '2026-07-19T15:00:00Z',
    analysis: {
      incidentType: 'Road Accident',
      severity: 'Low',
      confidence: 0.82,
      confidencePercent: 82,
      firstAid: [
        'Clean minor wounds with clean water.',
        'Apply antiseptic and bandage.',
        'Check for dizziness or head injury.',
      ],
      emergencyServices: ['Ambulance (108)'],
      recommendations: [
        'Incident classified as Road Accident with Low severity.',
        'Assign to routine response queue.',
      ],
    },
  },
  {
    id: 'INC-007',
    title: 'Building Wall Crack After Tremor',
    type: 'Earthquake',
    description: 'A mild tremor was felt in the area. A crack has appeared on the boundary wall of the school building. No injuries reported. Students have been evacuated as a precaution.',
    severity: 'Medium',
    status: 'Resolved',
    location: 'DPS School, Sector 45, Gurugram',
    contactNumber: '+91 9876543216',
    reportedBy: 'citizen-006',
    reporterName: 'Meera Joshi',
    confidence: 0.75,
    priorityScore: 3,
    imageUrl: null,
    createdAt: '2026-07-20T11:00:00Z',
    updatedAt: '2026-07-20T14:00:00Z',
    analysis: {
      incidentType: 'Earthquake',
      severity: 'Medium',
      confidence: 0.75,
      confidencePercent: 75,
      firstAid: [
        'Stay away from damaged structures.',
        'Be prepared for aftershocks.',
        'Check for gas leaks.',
      ],
      emergencyServices: ['NDRF', 'Structural Engineers'],
      recommendations: [
        'Incident classified as Earthquake with Medium severity.',
        'Deploy structural assessment team.',
      ],
    },
  },
  {
    id: 'INC-008',
    title: 'Chemical Spill at Factory',
    type: 'Chemical Spill',
    description: 'A tanker carrying industrial chemicals has overturned at the factory gate. Unknown liquid is spreading on the road. Strong smell in the area. Workers are reporting nausea and headaches. Area needs to be cordoned off immediately.',
    severity: 'High',
    status: 'Assigned',
    location: 'Industrial Area, Phase 3, Chandigarh',
    contactNumber: '+91 9876543217',
    reportedBy: 'citizen-007',
    reporterName: 'Arjun Nair',
    confidence: 0.88,
    priorityScore: 2,
    imageUrl: null,
    createdAt: '2026-07-21T06:00:00Z',
    updatedAt: '2026-07-21T06:30:00Z',
    analysis: {
      incidentType: 'Chemical Spill',
      severity: 'High',
      confidence: 0.88,
      confidencePercent: 88,
      firstAid: [
        'Evacuate upwind from the spill.',
        'Call hazmat teams immediately.',
        'Do NOT touch spilled chemicals.',
      ],
      emergencyServices: ['Hazmat Team', 'Fire Department (101)', 'Ambulance (108)'],
      recommendations: [
        'Incident classified as Chemical Spill with High severity.',
        'Immediate hazmat team dispatch recommended.',
      ],
    },
  },
];

export const ANALYTICS_DATA = {
  totalReports: 847,
  criticalReports: 124,
  resolvedReports: 589,
  pendingReports: 134,
  avgResponseTime: '12 min',
  resolutionRate: 69.5,
  reportsPerDay: [
    { date: 'Mon', reports: 42 },
    { date: 'Tue', reports: 38 },
    { date: 'Wed', reports: 55 },
    { date: 'Thu', reports: 47 },
    { date: 'Fri', reports: 63 },
    { date: 'Sat', reports: 35 },
    { date: 'Sun', reports: 29 },
  ],
  incidentsByType: [
    { name: 'Road Accident', value: 245, color: '#3b82f6' },
    { name: 'Fire', value: 156, color: '#ef4444' },
    { name: 'Medical', value: 189, color: '#22c55e' },
    { name: 'Flood', value: 98, color: '#06b6d4' },
    { name: 'Gas Leak', value: 67, color: '#f59e0b' },
    { name: 'Other', value: 92, color: '#8b5cf6' },
  ],
  severityDistribution: [
    { name: 'Critical', value: 124, color: '#ef4444' },
    { name: 'High', value: 234, color: '#f97316' },
    { name: 'Medium', value: 312, color: '#eab308' },
    { name: 'Low', value: 177, color: '#22c55e' },
  ],
  monthlyTrend: [
    { month: 'Jan', incidents: 68, resolved: 52 },
    { month: 'Feb', incidents: 72, resolved: 61 },
    { month: 'Mar', incidents: 85, resolved: 74 },
    { month: 'Apr', incidents: 79, resolved: 69 },
    { month: 'May', incidents: 92, resolved: 78 },
    { month: 'Jun', incidents: 88, resolved: 82 },
    { month: 'Jul', incidents: 95, resolved: 71 },
  ],
};
