import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart


def send_incident_email(incident: dict):
    """
    Sends an email notification to the emergency coordinator team when a new incident is reported.
    Uses SMTP configuration from environment variables. Falls back to console logging if not configured.
    """
    # Load configuration
    smtp_host = os.getenv("SMTP_HOST")
    smtp_port = os.getenv("SMTP_PORT")
    smtp_user = os.getenv("SMTP_USER")
    smtp_pass = os.getenv("SMTP_PASSWORD")
    recipient_email = os.getenv("COORDINATOR_EMAIL", "coordinator@resqai.com")
    from_email = os.getenv("FROM_EMAIL", "alerts@resqai.com")

    title = incident.get("title", "Emergency Incident")
    incident_id = incident.get("id", "Unknown ID")
    severity = incident.get("severity", "Medium")
    location = incident.get("location", "Unknown Location")
    description = incident.get("description", "")
    reporter_name = incident.get("reporter_name", "Anonymous")
    contact_number = incident.get("contact_number", "N/A")
    confidence = incident.get("confidence", 0.0)
    priority = incident.get("priority_score", 3)

    # HTML Email Template
    html_content = f"""
    <html>
      <body style="font-family: Arial, sans-serif; background-color: #f8fafc; color: #1e293b; padding: 20px;">
        <div style="max-width: 600px; margin: 0 auto; background-color: #ffffff; border: 1px solid #e2e8f0; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05);">
          <!-- Header -->
          <div style="background-color: {'#dc2626' if severity == 'Critical' else '#ea580c' if severity == 'High' else '#d97706' if severity == 'Medium' else '#16a34a'}; color: #ffffff; padding: 20px; text-align: center;">
            <h2 style="margin: 0; font-size: 20px;">🚨 NEW INCIDENT ALERT</h2>
            <p style="margin: 5px 0 0 0; font-size: 14px; opacity: 0.9;">Incident #{incident_id} [{severity}]</p>
          </div>
          
          <!-- Content -->
          <div style="padding: 24px; line-height: 1.6;">
            <h3 style="margin-top: 0; color: #0f172a; font-size: 18px;">{title}</h3>
            <p style="color: #475569; font-size: 14px; margin-bottom: 20px;">{description}</p>
            
            <table style="width: 100%; border-collapse: collapse; margin-bottom: 20px; font-size: 14px;">
              <tr style="border-bottom: 1px solid #f1f5f9;">
                <td style="padding: 10px 0; font-weight: bold; color: #64748b; width: 120px;">Location</td>
                <td style="padding: 10px 0; color: #0f172a;">📍 {location}</td>
              </tr>
              <tr style="border-bottom: 1px solid #f1f5f9;">
                <td style="padding: 10px 0; font-weight: bold; color: #64748b;">Reporter</td>
                <td style="padding: 10px 0; color: #0f172a;">👤 {reporter_name} ({contact_number})</td>
              </tr>
              <tr style="border-bottom: 1px solid #f1f5f9;">
                <td style="padding: 10px 0; font-weight: bold; color: #64748b;">AI Confidence</td>
                <td style="padding: 10px 0; color: #2563eb; font-weight: bold;">{int(confidence * 100)}%</td>
              </tr>
              <tr style="border-bottom: 1px solid #f1f5f9;">
                <td style="padding: 10px 0; font-weight: bold; color: #64748b;">Priority Score</td>
                <td style="padding: 10px 0; color: #0f172a;">Level {priority}/4</td>
              </tr>
            </table>

            <div style="background-color: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 15px; margin-top: 20px;">
              <h4 style="margin: 0 0 10px 0; color: #0f172a; font-size: 14px; display: flex; align-items: center;">💡 Dispatch Advice</h4>
              <p style="margin: 0; font-size: 13px; color: #475569;">
                Model recommends immediate routing of incident to nearest Trauma Care Center and notifying municipal emergency crew.
              </p>
            </div>
          </div>

          <!-- Footer -->
          <div style="background-color: #f1f5f9; padding: 15px; text-align: center; font-size: 11px; color: #94a3b8; border-top: 1px solid #e2e8f0;">
            <p style="margin: 0;">This is an automated alert generated by ResQ AI Crisis Management Platform.</p>
          </div>
        </div>
      </body>
    </html>
    """

    if not all([smtp_host, smtp_port, smtp_user, smtp_pass]):
        print(f"\n[EMAIL NOTIFICATION MOCK]")
        print(f"SMTP variables not set in .env. Falling back to log trace.")
        print(f"To: {recipient_email}")
        print(f"Subject: [ResQ AI Alert] {severity} Incident - #{incident_id} at {location}")
        print(f"Summary: {title} - {description[:60]}...")
        print(f"=====================================\n")
        return False

    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = f"[ResQ AI Alert] {severity} Incident - #{incident_id} at {location}"
        msg["From"] = from_email
        msg["To"] = recipient_email

        msg.attach(MIMEText(html_content, "html"))

        # Connect to SMTP Server
        server = smtplib.SMTP(smtp_host, int(smtp_port))
        server.starttls()
        server.login(smtp_user, smtp_pass)
        server.sendmail(from_email, recipient_email, msg.as_string())
        server.quit()
        
        print(f"Email notification sent successfully to {recipient_email} for Incident #{incident_id}")
        return True
    except Exception as e:
        print(f"Error sending email notification via SMTP: {e}")
        return False
